# Generated by Django 4.0.6 on 2022-07-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='U_ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='UserName')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
            ],
        ),
    ]
