# Generated by Django 4.0.6 on 2022-07-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='U_ID'),
        ),
    ]
