# Generated by Django 4.0.6 on 2022-07-23 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_remove_userinfo_id_alter_userinfo_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='join_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='join_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='gender'),
        ),
    ]
