# Generated by Django 4.0.6 on 2022-07-24 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_userinfo_avatar_alter_userinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='api_v1.user', verbose_name='U_ID')),
                ('follow', models.ManyToManyField(to='api_v1.user', verbose_name='follow')),
            ],
        ),
    ]
