# Generated by Django 4.0.6 on 2022-07-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_userfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollow',
            name='follow',
            field=models.ManyToManyField(related_name='+', to='api_v1.user', verbose_name='follow'),
        ),
    ]
