# Generated by Django 4.0.6 on 2022-07-24 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0009_alter_userfollow_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowed',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='api_v1.user', verbose_name='U_ID')),
                ('followed', models.ManyToManyField(related_name='+', to='api_v1.user', verbose_name='followed')),
            ],
        ),
    ]
