# Generated by Django 4.0.6 on 2022-07-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0010_userfollowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowed',
            name='followed',
        ),
        migrations.AddField(
            model_name='userfollowed',
            name='followed_by',
            field=models.ManyToManyField(related_name='+', to='api_v1.user', verbose_name='followed_by'),
        ),
    ]
