# Generated by Django 4.0.6 on 2022-07-24 04:36

import api_v1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0011_remove_userfollowed_followed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='P_ID')),
                ('pet_name', models.CharField(max_length=32, verbose_name='pet_name')),
                ('pet_avatar', models.ImageField(blank=True, max_length=256, null=True, upload_to=api_v1.models.avatar_dic_path, verbose_name='pet_avatar')),
                ('pet_gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='pet_gender')),
                ('pet_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='pet_age')),
                ('pet_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='pet_type')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.userinfo', verbose_name='master_id')),
            ],
        ),
    ]
