# Generated by Django 4.0.6 on 2022-07-25 21:56

import api_v1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0012_petinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('rid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='R_ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('r_type', models.PositiveSmallIntegerField(choices=[(1, 'article'), (2, 'picture'), (3, 'video')], verbose_name='resource_type')),
                ('views_count', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='numbers_of_views')),
                ('comments_count', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='numbers_of_comments')),
                ('likes_count', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='numbers_of_likes')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('media', models.FileField(blank=True, max_length=256, null=True, upload_to=api_v1.models.avatar_dic_path, verbose_name='media')),
                ('release_time', models.DateTimeField(auto_now_add=True, verbose_name='release_time')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.userinfo', verbose_name='publisher')),
            ],
        ),
    ]
