# Generated by Django 4.0.6 on 2022-07-26 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0013_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLike',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='api_v1.userinfo', verbose_name='U_ID')),
                ('follow', models.ManyToManyField(related_name='+', to='api_v1.resource', verbose_name='like_resource')),
            ],
        ),
    ]
