# Generated by Django 4.0.6 on 2022-07-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0014_resourcelike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcelike',
            old_name='follow',
            new_name='like',
        ),
    ]
