# Generated by Django 4.0.6 on 2022-07-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0015_rename_follow_resourcelike_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='C_ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.resource', verbose_name='resource')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.userinfo', verbose_name='publisher')),
            ],
        ),
    ]
